# Generated by Django 6.0.1 on 2026-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rate_rate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0.0), ('rate__lte', 5.0)), name='rate_between_0_and_5'),
        ),
    ]
