# Generated by Django 6.0.1 on 2026-01-22 07:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rate_rate_between_0_and_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.chat_image_path),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct')], default='direct', max_length=10),
        ),
    ]
