# Generated by Django 6.0.1 on 2026-01-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_image_alter_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='call_token',
        ),
        migrations.AddField(
            model_name='call',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('ended', 'Ended'), ('missed', 'Missed')], default='ringing', max_length=20),
        ),
    ]
