# Generated by Django 6.0.1 on 2026-02-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_call_call_token_call_answered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isPremium',
        ),
    ]
