# Generated by Django 6.0.1 on 2026-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deletedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='auto_delete_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
