# Generated by Django 6.0.1 on 2026-02-16 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chatparticipant_auto_delete_enabled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('ended', 'Ended')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
